#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from converter.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "converter.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h> 
#include "linkedlist.h"
#include "strings.h"
extern int yylex();
int yyerror(const char *);
int counter=0;
char *temp;
int lineNb=1,i; 
char* inhType; 
char* value;
int flag,N=0,n; 
char* str;
char *text;
char *newText,*buff;
node_t * symbolTable = NULL;
void verifyDoesntExist(char* id){
    if(contains(symbolTable,id) > 0 )
        yyerror(concat(id," already defined\n"));
    else
        push(&symbolTable,id);       
}
void verifyExists(char* id){
    if(contains(symbolTable,id) <=0 )
        yyerror(concat(id," is not defined\n"));      
}
char* indent(char* buff){
    char* res="";
    for(i=0;i<strlen(buff);i++)
        if(buff[i]=='\n')
            res=concat(res,"\n\t");
            else
            res=append(res,buff[i]);
    return res;
}

#line 40 "converter.y"
typedef union {
  char *strVal;
  struct {
  	char *varWithValues;
	char *varWithoutValues;
  } variables;
  struct {
  	char *expr;
	char *index;
  } forStruct;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	OPENSTRING	258
#define	INNERSTRING	259
#define	CLOSESTRING	260
#define	PURESTRING	261
#define	ID	262
#define	PRINT	263
#define	SCAN	264
#define	MAIN	265
#define	VOID	266
#define	INTEGER	267
#define	CHAR	268
#define	SINGLE	269
#define	DOUBLE	270
#define	INTEGERVALUE	271
#define	CHARVALUE	272
#define	SINGLEVALUE	273
#define	DOUBLEVALUE	274
#define	IF	275
#define	ELSE	276
#define	EQ	277
#define	LE	278
#define	GE	279
#define	AND	280
#define	OR	281
#define	ADD	282
#define	SUB	283
#define	MUL	284
#define	DIV	285
#define	INC	286
#define	DEC	287
#define	WHILE	288
#define	FOR	289


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int OPENSTRING;
static const int INNERSTRING;
static const int CLOSESTRING;
static const int PURESTRING;
static const int ID;
static const int PRINT;
static const int SCAN;
static const int MAIN;
static const int VOID;
static const int INTEGER;
static const int CHAR;
static const int SINGLE;
static const int DOUBLE;
static const int INTEGERVALUE;
static const int CHARVALUE;
static const int SINGLEVALUE;
static const int DOUBLEVALUE;
static const int IF;
static const int ELSE;
static const int EQ;
static const int LE;
static const int GE;
static const int AND;
static const int OR;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int INC;
static const int DEC;
static const int WHILE;
static const int FOR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,OPENSTRING=258
	,INNERSTRING=259
	,CLOSESTRING=260
	,PURESTRING=261
	,ID=262
	,PRINT=263
	,SCAN=264
	,MAIN=265
	,VOID=266
	,INTEGER=267
	,CHAR=268
	,SINGLE=269
	,DOUBLE=270
	,INTEGERVALUE=271
	,CHARVALUE=272
	,SINGLEVALUE=273
	,DOUBLEVALUE=274
	,IF=275
	,ELSE=276
	,EQ=277
	,LE=278
	,GE=279
	,AND=280
	,OR=281
	,ADD=282
	,SUB=283
	,MUL=284
	,DIV=285
	,INC=286
	,DEC=287
	,WHILE=288
	,FOR=289


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::OPENSTRING=258;
const int YY_parse_CLASS::INNERSTRING=259;
const int YY_parse_CLASS::CLOSESTRING=260;
const int YY_parse_CLASS::PURESTRING=261;
const int YY_parse_CLASS::ID=262;
const int YY_parse_CLASS::PRINT=263;
const int YY_parse_CLASS::SCAN=264;
const int YY_parse_CLASS::MAIN=265;
const int YY_parse_CLASS::VOID=266;
const int YY_parse_CLASS::INTEGER=267;
const int YY_parse_CLASS::CHAR=268;
const int YY_parse_CLASS::SINGLE=269;
const int YY_parse_CLASS::DOUBLE=270;
const int YY_parse_CLASS::INTEGERVALUE=271;
const int YY_parse_CLASS::CHARVALUE=272;
const int YY_parse_CLASS::SINGLEVALUE=273;
const int YY_parse_CLASS::DOUBLEVALUE=274;
const int YY_parse_CLASS::IF=275;
const int YY_parse_CLASS::ELSE=276;
const int YY_parse_CLASS::EQ=277;
const int YY_parse_CLASS::LE=278;
const int YY_parse_CLASS::GE=279;
const int YY_parse_CLASS::AND=280;
const int YY_parse_CLASS::OR=281;
const int YY_parse_CLASS::ADD=282;
const int YY_parse_CLASS::SUB=283;
const int YY_parse_CLASS::MUL=284;
const int YY_parse_CLASS::DIV=285;
const int YY_parse_CLASS::INC=286;
const int YY_parse_CLASS::DEC=287;
const int YY_parse_CLASS::WHILE=288;
const int YY_parse_CLASS::FOR=289;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		192
#define	YYFLAG		-32768
#define	YYNTBASE	50

#define YYTRANSLATE(x) ((unsigned)(x) <= 289 ? yytranslate[x] : 88)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    47,     2,     2,     2,     2,    42,     2,    35,
    36,    45,    43,    40,    44,     2,    46,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    39,    49,
    41,    48,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    37,     2,    38,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     8,    11,    12,    14,    16,    18,    20,    22,    24,
    28,    30,    32,    34,    37,    40,    43,    46,    49,    52,
    56,    62,    64,    68,    70,    72,    74,    76,    81,    83,
    86,    91,    95,    97,   103,   109,   114,   122,   130,   136,
   140,   144,   146,   150,   154,   156,   160,   163,   165,   167,
   171,   173,   177,   179,   182,   184,   188,   190,   194,   196,
   198,   200,   202,   204,   208,   211,   214,   216,   218,   220,
   222,   224,   230,   233,   236,   241,   247,   252,   257,   262,
   267,   272,   277,   281,   285,   287,   289,   291,   293,   295
};

static const short yyrhs[] = {    11,
    10,    35,    36,    37,    51,    38,     0,    52,    51,     0,
     0,    53,     0,    54,     0,    55,     0,    78,     0,    79,
     0,    65,     0,    37,    51,    38,     0,    66,     0,    87,
     0,    80,     0,    56,    39,     0,    59,    39,     0,    63,
    39,     0,    67,    39,     0,    76,    39,     0,    58,    57,
     0,    57,    40,     7,     0,    57,    40,     7,    41,    67,
     0,     7,     0,     7,    41,    67,     0,    12,     0,    13,
     0,    14,     0,    15,     0,     8,    35,    60,    36,     0,
     6,     0,     3,    61,     0,    62,    61,    40,    67,     0,
     5,    40,    67,     0,     4,     0,     9,    35,     3,    64,
    36,     0,     4,    64,    40,    42,     7,     0,     5,    40,
    42,     7,     0,    20,    35,    70,    36,    53,    21,    53,
     0,    20,    35,    70,    36,    53,    21,    66,     0,    20,
    35,    70,    36,    52,     0,    67,    43,    68,     0,    67,
    44,    68,     0,    68,     0,    68,    45,    69,     0,    68,
    46,    69,     0,    69,     0,    35,    67,    36,     0,    44,
    69,     0,     7,     0,    85,     0,    70,    26,    71,     0,
    71,     0,    71,    25,    72,     0,    72,     0,    47,    72,
     0,    73,     0,    35,    70,    36,     0,    74,     0,    67,
    75,    67,     0,    22,     0,    48,     0,    49,     0,    23,
     0,    24,     0,     7,    77,    67,     0,     7,    31,     0,
     7,    32,     0,    41,     0,    27,     0,    28,     0,    29,
     0,    30,     0,    33,    35,    70,    36,    53,     0,    81,
    53,     0,    81,    54,     0,    34,    82,    83,    84,     0,
    35,     7,    41,    67,    39,     0,     7,    23,    67,    39,
     0,     7,    24,    67,    39,     0,     7,    49,    67,    39,
     0,     7,    48,    67,    39,     0,     7,    27,    67,    36,
     0,     7,    28,    67,    36,     0,     7,    31,    36,     0,
     7,    32,    36,     0,    17,     0,    86,     0,    16,     0,
    18,     0,    19,     0,    33,    35,    70,    36,    54,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    68,    71,    72,    75,    76,    79,    80,    81,    82,    83,
    86,    87,    88,    91,    92,    93,    94,    95,    98,   108,
   112,   117,   121,   129,   130,   131,   132,   135,   138,   139,
   142,   146,   150,   153,   156,   158,   162,   169,   174,   180,
   181,   182,   185,   186,   187,   190,   191,   192,   193,   196,
   197,   200,   201,   204,   205,   208,   209,   212,   215,   216,
   217,   218,   219,   222,   223,   224,   227,   228,   229,   230,
   231,   235,   241,   245,   249,   264,   268,   269,   270,   275,
   282,   283,   288,   289,   293,   294,   297,   298,   299,   302
};

static const char * const yytname[] = {   "$","error","$illegal.","OPENSTRING",
"INNERSTRING","CLOSESTRING","PURESTRING","ID","PRINT","SCAN","MAIN","VOID","INTEGER",
"CHAR","SINGLE","DOUBLE","INTEGERVALUE","CHARVALUE","SINGLEVALUE","DOUBLEVALUE",
"IF","ELSE","EQ","LE","GE","AND","OR","ADD","SUB","MUL","DIV","INC","DEC","WHILE",
"FOR","'('","')'","'{'","'}'","';'","','","'='","'&'","'+'","'-'","'*'","'/'",
"'!'","'>'","'<'","start","code","line","stmt","openStmt","simpleStmt","declaration",
"varList","type","output","printfExpression","stringAndArguments","innerString",
"input","stringAndAddresses","ifStmt","openIfStmt","arithmaticExpression","term",
"factor","logicExpression","logicTerm","logicFactor","notFactor","comparator",
"comparisonOperator","assignment","assignementOperation","whileLoop","forLoop",
"openForLoop","forExpr","initExpr","boundExpr","stepExpr","value","numberValue",
"openWhileLoop",""
};
#endif

static const short yyr1[] = {     0,
    50,    51,    51,    52,    52,    53,    53,    53,    53,    53,
    54,    54,    54,    55,    55,    55,    55,    55,    56,    57,
    57,    57,    57,    58,    58,    58,    58,    59,    60,    60,
    61,    61,    62,    63,    64,    64,    65,    66,    66,    67,
    67,    67,    68,    68,    68,    69,    69,    69,    69,    70,
    70,    71,    71,    72,    72,    73,    73,    74,    75,    75,
    75,    75,    75,    76,    76,    76,    77,    77,    77,    77,
    77,    78,    79,    80,    81,    82,    83,    83,    83,    83,
    84,    84,    84,    84,    85,    85,    86,    86,    86,    87
};

static const short yyr2[] = {     0,
     7,     2,     0,     1,     1,     1,     1,     1,     1,     3,
     1,     1,     1,     2,     2,     2,     2,     2,     2,     3,
     5,     1,     3,     1,     1,     1,     1,     4,     1,     2,
     4,     3,     1,     5,     5,     4,     7,     7,     5,     3,
     3,     1,     3,     3,     1,     3,     2,     1,     1,     3,
     1,     3,     1,     2,     1,     3,     1,     3,     1,     1,
     1,     1,     1,     3,     2,     2,     1,     1,     1,     1,
     1,     5,     2,     2,     4,     5,     4,     4,     4,     4,
     4,     4,     3,     3,     1,     1,     1,     1,     1,     5
};

static const short yydefact[] = {     0,
     0,     0,     0,     0,     3,    48,     0,     0,    24,    25,
    26,    27,    87,    85,    88,    89,     0,     0,     0,     0,
     3,     0,     0,     3,     4,     5,     6,     0,     0,     0,
     0,     9,    11,     0,    42,    45,     0,     7,     8,    13,
     0,    49,    86,    12,    68,    69,    70,    71,    65,    66,
    67,     0,     0,     0,     0,     0,     0,     0,    48,     0,
     0,    47,     1,     2,    14,    22,    19,    15,    16,    17,
     0,     0,     0,     0,    18,    73,    74,    64,     0,    29,
     0,     0,     0,     0,     0,     0,    51,    53,    55,    57,
     0,     0,     0,     0,    46,    10,     0,     0,    40,    41,
    43,    44,    33,     0,    30,     0,    28,     0,     0,     0,
     0,     0,    54,    59,    62,    63,    60,    61,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    75,
    23,    20,     0,     0,     0,     0,    34,    56,    58,    50,
    39,     4,    52,    72,    90,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    32,     0,     0,     0,     0,
    76,    77,    78,    80,    79,     0,     0,    83,    84,    21,
    31,     0,    36,     0,    37,    38,     0,    81,    82,    35,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0
};

static const short yydefgoto[] = {   190,
    23,    24,    25,    26,    27,    28,    67,    29,    30,    81,
   105,   106,    31,   110,    32,    33,    34,    35,    36,    86,
    87,    88,    89,    90,   119,    37,    52,    38,    39,    40,
    41,    58,    94,   130,    42,    43,    44
};

static const short yypact[] = {    -3,
     0,    -6,     7,    15,    53,   112,    -1,    24,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    41,    54,    57,     2,
    53,     2,    58,    53,-32768,-32768,-32768,    62,    91,    79,
    83,-32768,-32768,   -32,    29,-32768,    86,-32768,-32768,-32768,
    53,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,     2,    21,   109,    -2,    -2,   123,   129,-32768,    14,
   107,-32768,-32768,-32768,-32768,   116,   120,-32768,-32768,-32768,
     2,     2,     2,     2,-32768,-32768,-32768,    90,   151,-32768,
   113,   164,    -2,    -2,    71,   -13,   137,-32768,-32768,-32768,
     4,   122,    30,   173,-32768,-32768,     2,   180,    29,    29,
-32768,-32768,-32768,   148,-32768,   151,-32768,   164,   149,   146,
   193,     5,-32768,-32768,-32768,-32768,-32768,-32768,     2,    -2,
    53,    -2,    53,     2,     2,     2,     2,     2,    96,-32768,
    90,   153,     2,   150,   156,   155,-32768,-32768,    90,   137,
-32768,   192,-32768,-32768,-32768,   108,   115,   140,   142,   175,
     2,     2,   165,   176,     2,    90,     2,   178,   214,   158,
-32768,-32768,-32768,-32768,-32768,    67,    73,-32768,-32768,    90,
    90,   215,-32768,   188,-32768,-32768,   191,-32768,-32768,-32768,
    -2,   195,    12,    -2,   191,    55,   191,   206,   191,   231,
   232,-32768
};

static const short yypgoto[] = {-32768,
    59,   117,   -39,   -38,-32768,-32768,-32768,-32768,-32768,-32768,
   127,-32768,-32768,   126,-32768,    80,   -20,   -46,   -18,   -55,
   119,   -78,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
  -138,-32768,-32768,-32768,-32768,-32768,-32768
};


#define	YYLAST		242


static const short yytable[] = {    60,
    91,    76,    77,    62,    59,   113,    70,     1,    59,     2,
    71,    72,   120,    13,    14,    15,    16,    13,    14,    15,
    16,   177,   121,    79,    99,   100,    80,   112,     3,   120,
   120,    78,    83,    53,    85,    85,    20,   120,   177,   123,
   138,    22,     4,   143,    84,    22,   177,   185,   177,    95,
   177,     5,   125,   126,   101,   102,    71,    72,    54,     6,
     7,     8,   111,    85,     9,    10,    11,    12,    13,    14,
    15,    16,    17,    73,    74,    55,   131,   127,   128,    61,
   120,   142,    64,   144,   145,    18,    19,    20,    56,    21,
   187,    57,   114,   115,   116,    63,    22,    66,   139,    85,
    65,    85,   178,   146,   147,   148,   149,   150,   179,    71,
    72,    82,   156,    71,    72,    71,    72,    68,   117,   118,
   175,    69,   151,   152,    75,   183,   153,   154,   186,    92,
   166,   167,    71,    72,   170,    93,   171,    76,    45,    46,
    47,    48,    49,    50,    96,   144,   161,   188,   107,   175,
    71,    72,    51,   162,   103,   104,    97,    71,    72,    98,
    85,   122,   124,    85,     6,     7,     8,   108,   109,     9,
    10,    11,    12,    13,    14,    15,    16,    17,   163,   129,
   164,   137,    71,    72,    71,    72,   132,   133,   136,   157,
   174,    19,    20,   155,    21,   158,   159,     6,     7,     8,
   168,    22,     9,    10,    11,    12,    13,    14,    15,    16,
   182,   169,   160,   165,   114,   115,   116,    71,    72,   172,
   173,   180,   181,   174,    19,    20,   189,    21,    95,   184,
   191,   192,   134,   135,    22,    71,    72,   141,   140,   176,
   117,   118
};

static const short yycheck[] = {    20,
    56,    41,    41,    22,     7,    84,    39,    11,     7,    10,
    43,    44,    26,    16,    17,    18,    19,    16,    17,    18,
    19,   160,    36,     3,    71,    72,     6,    83,    35,    26,
    26,    52,    35,    35,    55,    56,    35,    26,   177,    36,
    36,    44,    36,   122,    47,    44,   185,    36,   187,    36,
   189,    37,    23,    24,    73,    74,    43,    44,    35,     7,
     8,     9,    83,    84,    12,    13,    14,    15,    16,    17,
    18,    19,    20,    45,    46,    35,    97,    48,    49,    21,
    26,   121,    24,   123,   123,    33,    34,    35,    35,    37,
    36,    35,    22,    23,    24,    38,    44,     7,   119,   120,
    39,   122,    36,   124,   125,   126,   127,   128,    36,    43,
    44,     3,   133,    43,    44,    43,    44,    39,    48,    49,
   160,    39,    27,    28,    39,   181,    31,    32,   184,     7,
   151,   152,    43,    44,   155,     7,   157,   177,    27,    28,
    29,    30,    31,    32,    38,   185,    39,   187,    36,   189,
    43,    44,    41,    39,     4,     5,    41,    43,    44,    40,
   181,    25,    41,   184,     7,     8,     9,     4,     5,    12,
    13,    14,    15,    16,    17,    18,    19,    20,    39,     7,
    39,    36,    43,    44,    43,    44,     7,    40,    40,    40,
    33,    34,    35,    41,    37,    40,    42,     7,     8,     9,
    36,    44,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    36,    21,    39,    22,    23,    24,    43,    44,    42,
     7,     7,    35,    33,    34,    35,    21,    37,    36,    35,
     0,     0,   106,   108,    44,    43,    44,   121,   120,   160,
    48,    49
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 68 "converter.y"
{printf("Module VBModule\n\tSub Main()\n");
              printf("\t\t%s\n\tEnd Sub\nEnd Module\n",indent(indent(yyvsp[-1].strVal)));return(0);;
    break;}
case 2:
#line 71 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-1].strVal,"\n"),yyvsp[0].strVal);
    break;}
case 3:
#line 72 "converter.y"
{yyval.strVal="";  ;
    break;}
case 4:
#line 75 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 5:
#line 76 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 10:
#line 83 "converter.y"
{ yyval.strVal = yyvsp[-1].strVal ;
    break;}
case 19:
#line 98 "converter.y"
{ if(strcmp(yyvsp[0].variables.varWithoutValues,"")==0)
									str=strdup(yyvsp[0].variables.varWithValues);
								else if(strcmp(yyvsp[0].variables.varWithValues,"")==0)
										str=strdup(yyvsp[0].variables.varWithoutValues);
									else str=concat(concat(yyvsp[0].variables.varWithoutValues,concat(" As ",yyvsp[-1].strVal)),yyvsp[0].variables.varWithValues);
								yyval.strVal=concat("Dim ",str);
									
                            ;
    break;}
case 20:
#line 108 "converter.y"
{ verifyDoesntExist(yyvsp[0].strVal);
						  yyval.variables.varWithoutValues = concat(yyvsp[-2].variables.varWithoutValues,concat(" , ",yyvsp[0].strVal));
						  yyval.variables.varWithValues=yyvsp[-2].variables.varWithValues;
						 ;
    break;}
case 21:
#line 112 "converter.y"
{ verifyDoesntExist(yyvsp[-2].strVal);
							    temp = concat(concat(yyvsp[-2].strVal," As "),concat(inhType," = " ));
							    yyval.variables.varWithValues = concat(concat(yyvsp[-4].variables.varWithValues," , "),concat(temp,yyvsp[0].strVal));          
							  yyval.variables.varWithoutValues=yyvsp[-4].variables.varWithoutValues;
										   ;
    break;}
case 22:
#line 117 "converter.y"
{verifyDoesntExist(yyvsp[0].strVal);
	  yyval.variables.varWithoutValues = strdup(yyvsp[0].strVal);
	  yyval.variables.varWithValues="";
	 ;
    break;}
case 23:
#line 121 "converter.y"
{ verifyDoesntExist(yyvsp[-2].strVal);
							    temp = concat(concat(yyvsp[-2].strVal," As "),concat(inhType," = " ));
							    yyval.variables.varWithValues = concat(temp,yyvsp[0].strVal); 
							   yyval.variables.varWithoutValues="";
							   
							  ;
    break;}
case 24:
#line 129 "converter.y"
{inhType=strdup(yyvsp[0].strVal);;
    break;}
case 25:
#line 130 "converter.y"
{inhType=strdup(yyvsp[0].strVal);;
    break;}
case 26:
#line 131 "converter.y"
{inhType=strdup(yyvsp[0].strVal);;
    break;}
case 27:
#line 132 "converter.y"
{inhType=strdup(yyvsp[0].strVal);;
    break;}
case 28:
#line 135 "converter.y"
{yyval.strVal=concat(concat("Console.Write(",yyvsp[-1].strVal),")");;
    break;}
case 30:
#line 139 "converter.y"
{yyval.strVal=concat(yyvsp[-1].strVal,yyvsp[0].strVal);;
    break;}
case 31:
#line 142 "converter.y"
{
	yyval.strVal=concat(concat(concat(concat("{",stringValue(--counter)),"}"),yyvsp[-3].strVal),concat(yyvsp[-2].strVal,concat(",",yyvsp[0].strVal)));
	
;
    break;}
case 32:
#line 146 "converter.y"
{
	yyval.strVal=concat(concat(concat(concat("{",stringValue(counter)),"}"),yyvsp[-2].strVal),concat(",",yyvsp[0].strVal));;
    break;}
case 33:
#line 150 "converter.y"
{counter++;;
    break;}
case 34:
#line 153 "converter.y"
{yyval.strVal=yyvsp[-1].strVal;;
    break;}
case 35:
#line 157 "converter.y"
{ yyval.strVal = concat(yyvsp[-3].strVal,concat(concat("\n",yyvsp[0].strVal)," = Console.ReadLine()")); ;
    break;}
case 36:
#line 158 "converter.y"
{ yyval.strVal=concat(yyvsp[0].strVal," = Console.ReadLine()");;
    break;}
case 37:
#line 162 "converter.y"
{
                                 str = concat(concat("If ",yyvsp[-4].strVal)," Then\n\t");
                                 str = concat(str,concat(indent(yyvsp[-2].strVal),"\nElse\n\t"));
                                 yyval.strVal = concat(str,concat(indent(yyvsp[0].strVal),"\nEnd If"));
                                ;
    break;}
case 38:
#line 169 "converter.y"
{                 
                                str = concat(concat("If ",yyvsp[-4].strVal)," Then\n\t");
                                str = concat(str,concat(indent(yyvsp[-2].strVal),"\nElse\n\t"));
                                 yyval.strVal = concat(str,concat(indent(yyvsp[0].strVal),"\nEnd If"));
                                ;
    break;}
case 39:
#line 174 "converter.y"
{ 
                               str = concat(concat("If ",yyvsp[-2].strVal)," Then\n\t");
                               yyval.strVal = concat(str,concat(indent(yyvsp[0].strVal),"\nEnd If"));
                                ;
    break;}
case 40:
#line 180 "converter.y"
{ yyval.strVal=concat(yyvsp[-2].strVal,concat(strdup(" + "),yyvsp[0].strVal)); ;
    break;}
case 41:
#line 181 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-2].strVal," - "),yyvsp[0].strVal); ;
    break;}
case 42:
#line 182 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 43:
#line 185 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-2].strVal," * "),yyvsp[0].strVal);;
    break;}
case 44:
#line 186 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-2].strVal," / "),yyvsp[0].strVal);;
    break;}
case 45:
#line 187 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 46:
#line 190 "converter.y"
{ yyval.strVal=concat(concat("( ",yyvsp[-1].strVal)," )");;
    break;}
case 47:
#line 191 "converter.y"
{yyval.strVal=concat("-",yyvsp[0].strVal);;
    break;}
case 48:
#line 192 "converter.y"
{verifyExists(yyvsp[0].strVal); yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 49:
#line 193 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 50:
#line 196 "converter.y"
{yyval.strVal=concat(concat(yyvsp[-2].strVal," Or "),yyvsp[0].strVal); ;
    break;}
case 51:
#line 197 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 52:
#line 200 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-2].strVal," And "),yyvsp[0].strVal);;
    break;}
case 53:
#line 201 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 54:
#line 204 "converter.y"
{ yyval.strVal=concat("Not ",yyvsp[0].strVal); ;
    break;}
case 55:
#line 205 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 56:
#line 208 "converter.y"
{  yyval.strVal=concat(concat("( ",yyvsp[-1].strVal)," )");;
    break;}
case 57:
#line 209 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 58:
#line 212 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-2].strVal,yyvsp[-1].strVal),yyvsp[0].strVal);;
    break;}
case 59:
#line 215 "converter.y"
{yyval.strVal= " = " ;;
    break;}
case 60:
#line 216 "converter.y"
{yyval.strVal= " > " ;;
    break;}
case 61:
#line 217 "converter.y"
{yyval.strVal= " < " ;;
    break;}
case 62:
#line 218 "converter.y"
{yyval.strVal= " <= " ;;
    break;}
case 63:
#line 219 "converter.y"
{yyval.strVal= " >= " ;;
    break;}
case 64:
#line 222 "converter.y"
{ verifyExists(yyvsp[-2].strVal);yyval.strVal=concat(concat(yyvsp[-2].strVal,yyvsp[-1].strVal),yyvsp[0].strVal);;
    break;}
case 65:
#line 223 "converter.y"
{ verifyExists(yyvsp[-1].strVal);yyval.strVal=concat(yyvsp[-1].strVal," += 1 ");;
    break;}
case 66:
#line 224 "converter.y"
{ verifyExists(yyvsp[-1].strVal);yyval.strVal=concat(yyvsp[-1].strVal," -= 1 ");;
    break;}
case 67:
#line 227 "converter.y"
{yyval.strVal= " = " ;;
    break;}
case 68:
#line 228 "converter.y"
{yyval.strVal= " += " ;;
    break;}
case 69:
#line 229 "converter.y"
{yyval.strVal= " -= " ;;
    break;}
case 70:
#line 230 "converter.y"
{yyval.strVal= " *= " ;;
    break;}
case 71:
#line 231 "converter.y"
{yyval.strVal= " /= " ;;
    break;}
case 72:
#line 235 "converter.y"
{   str=concat("While ",yyvsp[-2].strVal);
                                                  str=concat(str,"\n\t");
                                                  str=concat(str,indent(yyvsp[0].strVal));
                                                  yyval.strVal=concat(str,"\nEnd While");;
    break;}
case 73:
#line 241 "converter.y"
{ str=concat(yyvsp[-1].forStruct.expr,indent(yyvsp[0].strVal));
                         yyval.strVal=concat(concat(str,"\nNext "),yyvsp[-1].forStruct.index);;
    break;}
case 74:
#line 245 "converter.y"
{ str=concat(yyvsp[-1].forStruct.expr,indent(yyvsp[0].strVal));
                                 yyval.strVal=concat(concat(str,"\nNext "),yyvsp[-1].forStruct.index);;
    break;}
case 75:
#line 249 "converter.y"
{if(strcmp(yyvsp[-2].forStruct.index,yyvsp[-1].forStruct.index)!=0
                                       || strcmp(yyvsp[-1].forStruct.index,yyvsp[0].forStruct.index)!=0 )
                                       yyerror(" Index of for loop must be the same ");
                                       str=concat("For ",yyvsp[-2].forStruct.index);
                                       str=concat(str," = ");
                                       str=concat(str,yyvsp[-2].forStruct.expr);
                                       str=concat(str," To ");
                                       str=concat(str,yyvsp[-1].forStruct.expr);
                                       str=concat(str," Step ");
                                       str=concat(str,yyvsp[0].forStruct.expr);
                                       yyval.forStruct.expr=concat(str,"\n\t");
                                       yyval.forStruct.index=yyvsp[-2].forStruct.index;
                                             ;
    break;}
case 76:
#line 264 "converter.y"
{ verifyExists(yyvsp[-3].strVal);
                                                yyval.forStruct.expr=yyvsp[-1].strVal;
                                                yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 77:
#line 268 "converter.y"
{yyval.forStruct.expr=yyvsp[-1].strVal;yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 78:
#line 269 "converter.y"
{yyval.forStruct.expr=yyvsp[-1].strVal;yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 79:
#line 270 "converter.y"
{if(isNumeric(yyvsp[-1].strVal,&n)!=-1)
                                            yyval.forStruct.expr=stringValue(n-1);
                                        else
                                            yyval.forStruct.expr=concat(yyvsp[-1].strVal," - 1");
                                  yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 80:
#line 275 "converter.y"
{if(isNumeric(yyvsp[-1].strVal,&n)!=-1)
                                            yyval.forStruct.expr=stringValue(n-1);
                                        else
                                            yyval.forStruct.expr=concat(yyvsp[-1].strVal," - 1");
                                  yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 81:
#line 282 "converter.y"
{yyval.forStruct.expr=strdup(yyvsp[-1].strVal);yyval.forStruct.index=yyvsp[-3].strVal;;
    break;}
case 82:
#line 283 "converter.y"
{if(isNumeric(yyvsp[-1].strVal,&n))
                                            yyval.forStruct.expr=stringValue(-n);
                                        else
                                            yyval.forStruct.expr=concat(concat("- ( ",yyvsp[-1].strVal)," )");
                                  yyval.forStruct.index=strdup(yyvsp[-3].strVal);;
    break;}
case 83:
#line 288 "converter.y"
{  yyval.forStruct.expr=strdup("1");yyval.forStruct.index=strdup(yyvsp[-2].strVal);;
    break;}
case 84:
#line 289 "converter.y"
{  yyval.forStruct.expr=strdup("-1");yyval.forStruct.index=strdup(yyvsp[-2].strVal);;
    break;}
case 85:
#line 293 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 86:
#line 294 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 87:
#line 297 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 88:
#line 298 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 89:
#line 299 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 90:
#line 302 "converter.y"
{   str=concat("While ",yyvsp[-2].strVal);
                                                       str=concat(str,"\n\t");
                                                       buff=yyvsp[0].strVal;
                                                       for(i=0;i<strlen(buff);i++)
                                                          if(buff[i]=='\n')
                                                              str=concat(str,"\n\t");
                                                           else
                                                               str=append(str,buff[i]);
                                                        yyval.strVal=concat(str,"\nEnd While");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 315 "converter.y"


int main(){yyparse();return -1;}
int yyerror(const char*s){fprintf(stderr,"%s\n",s);return -1;}






