#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from testCv.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "testCv.y"

#include <stdio.h>
#include "linkedlist.h"
#include <string.h>
int lineNb=1,i,counter;
int yyerror();
int yylex();
node_t * variablesStack = NULL;      
node_t * variablesWithValuesStack = NULL;  
node_t * variablesValuesStack = NULL;  
char* variable; 
char* value;
int flag; 
char *text;
char *newText,*buff;

#line 18 "testCv.y"
typedef union
{
    int intValue;
    float floatValue;
   char* stringValue;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	Integer	258
#define	Char	259
#define	Single	260
#define	Double	261
#define	Id	262
#define	NewLine	263
#define	IntegerValue	264
#define	CharacterValue	265
#define	SingleValue	266
#define	DoubleValue	267
#define	Print	268
#define	Scan	269
#define	Text	270
#define	Address	271
#define	If	272
#define	ELSE	273
#define	EQ	274
#define	LE	275
#define	GE	276
#define	AND	277
#define	OR	278
#define	ADD	279
#define	While	280
#define	For	281


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int Integer;
static const int Char;
static const int Single;
static const int Double;
static const int Id;
static const int NewLine;
static const int IntegerValue;
static const int CharacterValue;
static const int SingleValue;
static const int DoubleValue;
static const int Print;
static const int Scan;
static const int Text;
static const int Address;
static const int If;
static const int ELSE;
static const int EQ;
static const int LE;
static const int GE;
static const int AND;
static const int OR;
static const int ADD;
static const int While;
static const int For;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,Integer=258
	,Char=259
	,Single=260
	,Double=261
	,Id=262
	,NewLine=263
	,IntegerValue=264
	,CharacterValue=265
	,SingleValue=266
	,DoubleValue=267
	,Print=268
	,Scan=269
	,Text=270
	,Address=271
	,If=272
	,ELSE=273
	,EQ=274
	,LE=275
	,GE=276
	,AND=277
	,OR=278
	,ADD=279
	,While=280
	,For=281


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::Integer=258;
const int YY_parse_CLASS::Char=259;
const int YY_parse_CLASS::Single=260;
const int YY_parse_CLASS::Double=261;
const int YY_parse_CLASS::Id=262;
const int YY_parse_CLASS::NewLine=263;
const int YY_parse_CLASS::IntegerValue=264;
const int YY_parse_CLASS::CharacterValue=265;
const int YY_parse_CLASS::SingleValue=266;
const int YY_parse_CLASS::DoubleValue=267;
const int YY_parse_CLASS::Print=268;
const int YY_parse_CLASS::Scan=269;
const int YY_parse_CLASS::Text=270;
const int YY_parse_CLASS::Address=271;
const int YY_parse_CLASS::If=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::EQ=274;
const int YY_parse_CLASS::LE=275;
const int YY_parse_CLASS::GE=276;
const int YY_parse_CLASS::AND=277;
const int YY_parse_CLASS::OR=278;
const int YY_parse_CLASS::ADD=279;
const int YY_parse_CLASS::While=280;
const int YY_parse_CLASS::For=281;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		148
#define	YYFLAG		-32768
#define	YYNTBASE	43

#define YYTRANSLATE(x) ((unsigned)(x) <= 281 ? yytranslate[x] : 74)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    36,     2,     2,     2,    33,    42,     2,    34,
    35,    31,    29,    41,    30,     2,    32,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    40,    38,
    39,    37,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    27,     2,    28,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    10,    12,    14,    16,    18,
    22,    26,    33,    40,    43,    46,    54,    60,    68,    72,
    76,    78,    82,    86,    90,    92,    96,    98,   101,   103,
   107,   109,   113,   115,   118,   120,   124,   126,   130,   132,
   134,   136,   138,   140,   144,   150,   152,   154,   156,   160,
   176,   178,   180,   182,   186,   189,   194,   197,   198,   200,
   202,   204,   206,   208,   210,   212,   214,   218,   219,   224,
   225,   228,   230,   233,   235,   237,   240
};

static const short yyrhs[] = {    44,
     0,    45,    44,     0,     0,    46,     0,    49,     0,    47,
     0,    60,     0,    62,     0,    48,     0,    27,    44,    28,
     0,    66,    64,    70,     0,    13,    72,    15,    68,    71,
    70,     0,    14,    72,    15,    69,    71,    70,     0,    50,
    70,     0,    59,    70,     0,    17,    72,    53,    71,    46,
    73,    46,     0,    17,    72,    53,    71,    45,     0,    17,
    72,    53,    71,    46,    73,    49,     0,    50,    29,    51,
     0,    50,    30,    51,     0,    51,     0,    51,    31,    52,
     0,    51,    32,    52,     0,    51,    33,    52,     0,    52,
     0,    34,    50,    35,     0,     7,     0,    30,     7,     0,
    67,     0,    53,    23,    54,     0,    54,     0,    54,    22,
    55,     0,    55,     0,    36,    55,     0,    56,     0,    34,
    53,    35,     0,    57,     0,    50,    58,    50,     0,    19,
     0,    37,     0,    38,     0,    20,     0,    21,     0,     7,
    39,    50,     0,    25,    34,    53,    35,    61,     0,    60,
     0,    47,     0,    62,     0,    27,    44,    28,     0,    26,
    72,     7,    39,    67,    40,     7,    20,    67,    40,     7,
    24,    67,    71,    63,     0,    62,     0,    47,     0,    60,
     0,    27,    44,    28,     0,     7,    65,     0,     7,    39,
    67,    65,     0,    41,    64,     0,     0,     3,     0,     4,
     0,     5,     0,     6,     0,     9,     0,    10,     0,    11,
     0,    12,     0,    41,     7,    68,     0,     0,    41,    42,
     7,    69,     0,     0,    40,     8,     0,    40,     0,    35,
     8,     0,    35,     0,    34,     0,    18,     8,     0,    18,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    30,    34,    37,    40,    41,    44,    45,    46,    47,    48,
    51,    78,   113,   137,   138,   141,   152,   159,   170,   174,
   178,   181,   185,   189,   193,   196,   200,   201,   204,   207,
   211,   214,   218,   221,   224,   227,   231,   234,   240,   241,
   242,   243,   244,   247,   253,   259,   260,   261,   262,   265,
   282,   283,   284,   285,   290,   291,   294,   295,   298,   299,
   300,   301,   304,   305,   306,   307,   309,   310,   313,   314,
   317,   318,   320,   321,   323,   326,   327
};

static const char * const yytname[] = {   "$","error","$illegal.","Integer",
"Char","Single","Double","Id","NewLine","IntegerValue","CharacterValue","SingleValue",
"DoubleValue","Print","Scan","Text","Address","If","ELSE","EQ","LE","GE","AND",
"OR","ADD","While","For","'{'","'}'","'+'","'-'","'*'","'/'","'%'","'('","')'",
"'!'","'>'","'<'","'='","';'","','","'&'","start","Code","Line","Statement",
"SimpleStatement","ClosedIfStatement","OpenIfStatement","ArithmaticExpression",
"Term","Factor","LogicExpression","LogicTerm","LogicFactor","NotFactor","Comparator",
"Operation","Assignment","WhileLoop","WhileStatement","ForLoop","ForStatement",
"Variables","List","DataType","Value","Arguments","Addresses","End","RP","LP",
"Else",""
};
#endif

static const short yyr1[] = {     0,
    43,    44,    44,    45,    45,    46,    46,    46,    46,    46,
    47,    47,    47,    47,    47,    48,    49,    49,    50,    50,
    50,    51,    51,    51,    51,    52,    52,    52,    52,    53,
    53,    54,    54,    55,    55,    56,    56,    57,    58,    58,
    58,    58,    58,    59,    60,    61,    61,    61,    61,    62,
    63,    63,    63,    63,    64,    64,    65,    65,    66,    66,
    66,    66,    67,    67,    67,    67,    68,    68,    69,    69,
    70,    70,    71,    71,    72,    73,    73
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     1,     1,     1,     1,     1,     3,
     3,     6,     6,     2,     2,     7,     5,     7,     3,     3,
     1,     3,     3,     3,     1,     3,     1,     2,     1,     3,
     1,     3,     1,     2,     1,     3,     1,     3,     1,     1,
     1,     1,     1,     3,     5,     1,     1,     1,     3,    15,
     1,     1,     1,     3,     2,     4,     2,     0,     1,     1,
     1,     1,     1,     1,     1,     1,     3,     0,     4,     0,
     2,     1,     2,     1,     1,     2,     1
};

static const short yydefact[] = {     3,
    59,    60,    61,    62,    27,    63,    64,    65,    66,     0,
     0,     0,     0,     0,     3,     0,     0,     1,     3,     4,
     6,     9,     5,     0,    21,    25,     0,     7,     8,     0,
    29,     0,    75,     0,     0,     0,     0,     0,     0,    28,
    27,     0,     2,     0,     0,    72,    14,     0,     0,     0,
    15,    58,     0,    44,    68,    70,     0,     0,     0,     0,
    31,    33,    35,    37,     0,     0,    10,    26,    19,    20,
    71,    22,    23,    24,     0,     0,    55,    11,     0,     0,
     0,     0,     0,     0,    34,    39,    42,    43,    40,    41,
     0,     0,    74,     0,     0,     0,     0,    58,    57,    68,
     0,     0,     0,    36,    38,    30,    73,    17,     4,    32,
     3,    47,    46,    45,    48,     0,    56,    67,    12,    70,
    13,    77,     0,     0,     0,    69,    76,    16,    18,    49,
     0,     0,     0,     0,     0,     0,     0,     0,     3,    52,
    53,    51,    50,     0,    54,     0,     0,     0
};

static const short yydefgoto[] = {   146,
    18,    19,    20,    21,    22,    23,    24,    25,    26,    60,
    61,    62,    63,    64,    91,    27,    28,   114,    29,   143,
    53,    77,    30,    31,    80,    82,    47,    94,    34,   123
};

static const short yypact[] = {    80,
-32768,-32768,-32768,-32768,   -27,-32768,-32768,-32768,-32768,   -19,
   -19,   -19,     9,   -19,    80,    39,    27,-32768,    80,-32768,
-32768,-32768,-32768,    15,    70,-32768,   -18,-32768,-32768,    46,
-32768,    27,-32768,    47,    58,    18,    18,    74,    67,-32768,
-32768,    35,-32768,    27,    27,    96,-32768,    27,    27,    27,
-32768,    17,   -18,   -12,    77,    90,    18,    18,    79,    -9,
    66,-32768,-32768,-32768,    -4,    76,-32768,-32768,    70,    70,
-32768,-32768,-32768,-32768,    57,    46,-32768,-32768,   125,    98,
    92,    98,   150,     0,-32768,-32768,-32768,-32768,-32768,-32768,
    27,    18,   127,    80,    18,   116,    57,    95,-32768,    77,
   -18,   130,   -18,-32768,   -12,    66,-32768,-32768,   120,-32768,
    80,-32768,-32768,-32768,-32768,    99,-32768,-32768,-32768,    90,
-32768,   132,    80,   117,   137,-32768,-32768,-32768,-32768,-32768,
   128,    57,   107,   142,   139,    57,    98,   148,    80,-32768,
-32768,-32768,-32768,   136,-32768,   156,   165,-32768
};

static const short yypgoto[] = {-32768,
   -15,    72,   -83,   -89,-32768,    44,   -16,    33,    63,   -24,
    84,   -48,-32768,-32768,-32768,-32768,   -88,-32768,   -87,-32768,
   101,    83,-32768,   -73,    68,    52,   -21,   -77,    60,-32768
};


#define	YYLAST		188


static const short yytable[] = {    39,
    42,    98,   101,    43,   103,    51,   112,   113,   115,    85,
   109,    32,    65,    92,    33,    54,    44,    45,    92,    59,
    59,    46,    92,   116,    41,    93,     6,     7,     8,     9,
    96,    78,    84,    41,   104,     6,     7,     8,     9,   128,
    83,    59,    37,    44,    45,    40,   110,    16,   140,   141,
   142,    57,    52,    58,    46,    75,    16,    76,   133,   138,
    17,    55,   137,    44,    45,     6,     7,     8,     9,    68,
    35,    36,    56,    38,   105,    59,    69,    70,    59,   119,
    66,   121,     1,     2,     3,     4,     5,    95,     6,     7,
     8,     9,    10,    11,    67,   124,    12,    86,    87,    88,
    48,    49,    50,    71,    13,    14,    15,    44,    45,    16,
    72,    73,    74,    17,    97,    89,    90,    79,     1,     2,
     3,     4,     5,   144,     6,     7,     8,     9,    10,    11,
    81,   100,    93,   102,   107,    76,   120,   122,   125,   127,
    13,    14,   111,   131,   130,    16,   134,   132,   135,    17,
     1,     2,     3,     4,     5,   147,     6,     7,     8,     9,
    10,    11,   136,   145,   148,   108,   129,   118,    86,    87,
    88,   126,    13,    14,   139,   106,    99,    16,    44,    45,
   117,    17,     0,     0,    68,     0,    89,    90
};

static const short yycheck[] = {    15,
    17,    75,    80,    19,    82,    27,    96,    96,    96,    58,
    94,    39,    37,    23,    34,    32,    29,    30,    23,    36,
    37,    40,    23,    97,     7,    35,     9,    10,    11,    12,
    35,    53,    57,     7,    35,     9,    10,    11,    12,   123,
    57,    58,    34,    29,    30,     7,    95,    30,   138,   138,
   138,    34,     7,    36,    40,    39,    30,    41,   132,   137,
    34,    15,   136,    29,    30,     9,    10,    11,    12,    35,
    11,    12,    15,    14,    91,    92,    44,    45,    95,   101,
     7,   103,     3,     4,     5,     6,     7,    22,     9,    10,
    11,    12,    13,    14,    28,   111,    17,    19,    20,    21,
    31,    32,    33,     8,    25,    26,    27,    29,    30,    30,
    48,    49,    50,    34,    39,    37,    38,    41,     3,     4,
     5,     6,     7,   139,     9,    10,    11,    12,    13,    14,
    41,     7,    35,    42,     8,    41,     7,    18,    40,     8,
    25,    26,    27,     7,    28,    30,    40,    20,     7,    34,
     3,     4,     5,     6,     7,     0,     9,    10,    11,    12,
    13,    14,    24,    28,     0,    94,   123,   100,    19,    20,
    21,   120,    25,    26,    27,    92,    76,    30,    29,    30,
    98,    34,    -1,    -1,    35,    -1,    37,    38
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 30 "testCv.y"
{printf("valid\n");
              printf("%s\n",yyvsp[0].stringValue);return(0);;
    break;}
case 2:
#line 34 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue);
                                  strcat(yyval.stringValue,strdup("\n"));
                                 strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
    break;}
case 3:
#line 37 "testCv.y"
{yyval.stringValue=strdup(" ");  ;
    break;}
case 6:
#line 44 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);;
    break;}
case 7:
#line 45 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue); ;
    break;}
case 8:
#line 46 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);  ;
    break;}
case 9:
#line 47 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue); ;
    break;}
case 10:
#line 48 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue); ;
    break;}
case 11:
#line 51 "testCv.y"
{ 
                                              yyval.stringValue=strdup("Dim "); 
                                              flag=0;
                                              variable=pop(&variablesStack);
                                              if(variable){
                                                flag=1;
                                                strcat(yyval.stringValue,strdup(variable));
                                                variable=pop(&variablesStack);
                                                while(variable){ 
                                                sprintf(yyval.stringValue,"%s , %s",strdup(yyval.stringValue),strdup(variable));
                                                variable=pop(&variablesStack);  
                                                }
                                               strcat(yyval.stringValue," As ");
                                               strcat(yyval.stringValue,strdup(yyvsp[-2].stringValue));
                                             }
                                             variable=pop(&variablesWithValuesStack);
                                             value=pop(&variablesValuesStack);
                                             while(variable){
                                                if(flag)
                                                     strcat(yyval.stringValue,", ");
                                                sprintf(yyval.stringValue,"%s%s As %s = %s ",strdup(yyval.stringValue),
                                                strdup(variable),strdup(yyvsp[-2].stringValue),strdup(value));
                                                variable=pop(&variablesWithValuesStack);
                                                value=pop(&variablesValuesStack);
                                                flag=1;
                                             }
                                        ;
    break;}
case 12:
#line 78 "testCv.y"
{ 
                                    yyval.stringValue=strdup("Console.Write(");
                                    text=yyvsp[-3].stringValue;
                                    counter=0;
                                    for(i=0;i<strlen(text);i++)
                                        if(text[i]=='\\' && text[i+1]=='n'){
                                            strcat(yyval.stringValue,strdup("\"& vbcrlf &\""));
                                            i++;
                                        }
                                            
                                        else if(text[i]=='%' && (text[i+1]=='d' || text[i+1]=='c' || text[i+1]=='f' 
                                                                 || (text[i+1]=='l' && text[i+2]=='f' && (i=i+1) )))
                                        {  
                                           sprintf(yyval.stringValue, "%s{%d}",strdup(yyval.stringValue),counter);
                                           counter++;
                                           i+=1;
                                        }
                                        else
                                            strncat(yyval.stringValue,strdup(text+i), 1);
                                   
                                    while(counter > 0){
                                       variable=pop(&variablesStack);
                                       if(variable)
                                           sprintf(yyval.stringValue, "%s,%s",strdup(yyval.stringValue),strdup(variable));
                                       else
                                           yyerror("Not enough arguments");
                                       counter--;
                                   }
                                   if(pop(&variablesStack))
                                       yyerror("Too many arguments");
                                   
                                     strcat(yyval.stringValue,strdup(") "));
                                     strcat(yyval.stringValue,strdup(" "));
                                    // printf(".");
                                  ;
    break;}
case 13:
#line 113 "testCv.y"
{  yyval.stringValue=strdup("");
                                    text=yyvsp[-3].stringValue;
                                    for(i=1;i<strlen(text)-1;i++)
                                        if(text[i]==' ')
                                            continue;
                                        else if(text[i]=='%' && (text[i+1]=='d' || text[i+1]=='c' || text[i+1]=='f' 
                                                                 || (text[i+1]=='l' && text[i+2]=='f' && (i=i+1) )))
                                        { 
                                          variable=pop(&variablesStack);
                                          if(variable){
                                          strcat(yyval.stringValue,strdup(variable));
                                             strcat(yyval.stringValue,strdup(" = Console.ReadLine()\t"));
                                          }
                                          else
                                           yyerror("Not enough arguments");
                                           i+=1;
                                        }
                                       else{
                                          yyerror("Invalid string in scanf");
                                           break;
                                       }
                                   if(pop(&variablesStack))
                                       yyerror("Too many arguments");
                                  ;
    break;}
case 14:
#line 137 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue); ;
    break;}
case 15:
#line 138 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue); ;
    break;}
case 16:
#line 141 "testCv.y"
{
                                yyval.stringValue=strdup("If ");
                                strcat(yyval.stringValue,strdup(yyvsp[-4].stringValue));
                                strcat(yyval.stringValue,strdup(" Then\n    "));
                                strcat(yyval.stringValue,strdup(yyvsp[-2].stringValue));
                                strcat(yyval.stringValue,strdup(" \nElse\n    "));
                                strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
                                strcat(yyval.stringValue,strdup("\nEnd If"));
                                ;
    break;}
case 17:
#line 152 "testCv.y"
{ 
                               yyval.stringValue=strdup("If ");
                                strcat(yyval.stringValue,strdup(yyvsp[-2].stringValue));
                                strcat(yyval.stringValue,strdup(" Then\n    "));
                                strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
                                strcat(yyval.stringValue,strdup("\nEnd If"));
                                ;
    break;}
case 18:
#line 159 "testCv.y"
{
                                yyval.stringValue=strdup("If ");
                                strcat(yyval.stringValue,strdup(yyvsp[-4].stringValue));
                                strcat(yyval.stringValue,strdup(" Then\n    "));
                                strcat(yyval.stringValue,strdup(yyvsp[-1].stringValue));
                                strcat(yyval.stringValue,strdup("\nElse    "));
                                strcat(yyval.stringValue,strdup(yyvsp[3].stringValue));
                                strcat(yyval.stringValue,strdup("\nEnd If"));
                                ;
    break;}
case 19:
#line 170 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                                   strcat(yyval.stringValue," + ");
                                   strcat(yyval.stringValue,yyvsp[0].stringValue);
                                  ;
    break;}
case 20:
#line 174 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                                   strcat(yyval.stringValue," - ");
                                   strcat(yyval.stringValue,yyvsp[0].stringValue);
                                  ;
    break;}
case 22:
#line 181 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                             strcat(yyval.stringValue," * ");
                             strcat(yyval.stringValue,yyvsp[0].stringValue);
                            ;
    break;}
case 23:
#line 185 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                             strcat(yyval.stringValue," / ");
                             strcat(yyval.stringValue,yyvsp[0].stringValue);
                            ;
    break;}
case 24:
#line 189 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                             strcat(yyval.stringValue," Mod ");
                             strcat(yyval.stringValue,yyvsp[0].stringValue);
                            ;
    break;}
case 26:
#line 196 "testCv.y"
{ yyval.stringValue=strdup("( ");
                              strcat(yyval.stringValue,yyvsp[-1].stringValue);
                              strcat(yyval.stringValue," )");
                             ;
    break;}
case 27:
#line 200 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue); ;
    break;}
case 28:
#line 201 "testCv.y"
{ yyval.stringValue=strdup("-");
            strcat(yyval.stringValue,yyvsp[0].stringValue);
           ;
    break;}
case 29:
#line 204 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue); ;
    break;}
case 30:
#line 207 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                                                   strcat(yyval.stringValue," Or ");
                                                   strcat(yyval.stringValue,yyvsp[0].stringValue);
                                                  ;
    break;}
case 32:
#line 214 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                                          strcat(yyval.stringValue," And ");
                                          strcat(yyval.stringValue,yyvsp[0].stringValue);
                                         ;
    break;}
case 34:
#line 221 "testCv.y"
{ yyval.stringValue=strdup("Not ");
                               strcat(yyval.stringValue,yyvsp[0].stringValue);
                             ;
    break;}
case 36:
#line 227 "testCv.y"
{ yyval.stringValue=strdup("( ");
                                        strcat(yyval.stringValue,yyvsp[-1].stringValue);
                                        strcat(yyval.stringValue," )");
                                       ;
    break;}
case 38:
#line 234 "testCv.y"
{ yyval.stringValue=yyvsp[-2].stringValue;
                                                                    strcat(yyval.stringValue,yyvsp[-1].stringValue);
                                                                    strcat(yyval.stringValue,yyvsp[0].stringValue);
                                                                   ;
    break;}
case 39:
#line 240 "testCv.y"
{yyval.stringValue= " = " ;;
    break;}
case 40:
#line 241 "testCv.y"
{yyval.stringValue= " > " ;;
    break;}
case 41:
#line 242 "testCv.y"
{yyval.stringValue= " < " ;;
    break;}
case 42:
#line 243 "testCv.y"
{yyval.stringValue= " <= " ;;
    break;}
case 43:
#line 244 "testCv.y"
{yyval.stringValue= " >= " ;;
    break;}
case 44:
#line 247 "testCv.y"
{ yyval.stringValue=strdup(yyvsp[-2].stringValue);
                                              strcat(yyval.stringValue,strdup(" = "));
                                              strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
                                  ;
    break;}
case 45:
#line 253 "testCv.y"
{  yyval.stringValue=strdup("while ");
                                                           strcat(yyval.stringValue,strdup(yyvsp[-2].stringValue));
                                                           strcat(yyval.stringValue,strdup("\n\t"));
                                                           strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
                                                           strcat(yyval.stringValue,strdup("\nEnd While"));;
    break;}
case 47:
#line 260 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);;
    break;}
case 48:
#line 261 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);;
    break;}
case 49:
#line 262 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue);;
    break;}
case 50:
#line 266 "testCv.y"
{  if(strcmp(yyvsp[-12].stringValue,yyvsp[-8].stringValue)!=0
                                                            || strcmp(yyvsp[-8].stringValue,yyvsp[-4].stringValue)!=0 )
                                                            yyerror(" Index of for loop must be the same ");
                                                           yyval.stringValue=strdup("For  ");
                                                           strcat(yyval.stringValue,strdup(yyvsp[-12].stringValue));
                                                           strcat(yyval.stringValue,strdup(" = "));
                                                           strcat(yyval.stringValue,strdup(yyvsp[-10].stringValue));
                                                           strcat(yyval.stringValue,strdup(" To "));
                                                           strcat(yyval.stringValue,strdup(yyvsp[-6].stringValue));
                                                           strcat(yyval.stringValue,strdup(" step "));
                                                           strcat(yyval.stringValue,strdup(yyvsp[-2].stringValue));
                                                           strcat(yyval.stringValue,strdup("\n\t"));
                                                           strcat(yyval.stringValue,strdup(yyvsp[0].stringValue));
                                                           strcat(yyval.stringValue,strdup("\nNext "));
                                                           strcat(yyval.stringValue,strdup(yyvsp[-12].stringValue));;
    break;}
case 52:
#line 283 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);;
    break;}
case 53:
#line 284 "testCv.y"
{yyval.stringValue=strdup(yyvsp[0].stringValue);;
    break;}
case 54:
#line 285 "testCv.y"
{yyval.stringValue=strdup(yyvsp[-1].stringValue);;
    break;}
case 55:
#line 290 "testCv.y"
{ push(&variablesStack,yyvsp[-1].stringValue); ;
    break;}
case 56:
#line 291 "testCv.y"
{ push(&variablesWithValuesStack,yyvsp[-3].stringValue);
                      push(&variablesValuesStack,yyvsp[-1].stringValue); ;
    break;}
case 67:
#line 309 "testCv.y"
{ push(&variablesStack,yyvsp[-1].stringValue); ;
    break;}
case 69:
#line 313 "testCv.y"
{ push(&variablesStack,yyvsp[-1].stringValue); ;
    break;}
case 71:
#line 317 "testCv.y"
{lineNb++;;
    break;}
case 73:
#line 320 "testCv.y"
{lineNb++;;
    break;}
case 76:
#line 326 "testCv.y"
{lineNb++;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 329 "testCv.y"

int yyerror(char* s){fprintf(stderr,"line %d :%s\n",lineNb,s);}
int main(void){ yyparse();}
