#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from converter.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "converter.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h> 
#include "linkedlist.h"
#include "strings.h"
int lineNb=1,i,counter;
int yyerror();
int yylex();
int indent=0;
node_t * variablesStack = NULL;      
node_t * variablesWithValuesStack = NULL;  
node_t * variablesValuesStack = NULL;  
char* variable; 
char* value;
int flag,N=0; 
char* str;
char *text;
char *newText,*buff;

#line 22 "converter.y"
typedef union
{
   char* strVal;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	Integer	258
#define	Char	259
#define	Single	260
#define	Double	261
#define	Id	262
#define	IntegerValue	263
#define	CharacterValue	264
#define	SingleValue	265
#define	DoubleValue	266
#define	Print	267
#define	Scan	268
#define	Text	269
#define	Address	270
#define	If	271
#define	Else	272
#define	EQ	273
#define	LE	274
#define	GE	275
#define	AND	276
#define	OR	277
#define	ADD	278
#define	SUB	279
#define	INC	280
#define	DEC	281
#define	While	282
#define	For	283


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int Integer;
static const int Char;
static const int Single;
static const int Double;
static const int Id;
static const int IntegerValue;
static const int CharacterValue;
static const int SingleValue;
static const int DoubleValue;
static const int Print;
static const int Scan;
static const int Text;
static const int Address;
static const int If;
static const int Else;
static const int EQ;
static const int LE;
static const int GE;
static const int AND;
static const int OR;
static const int ADD;
static const int SUB;
static const int INC;
static const int DEC;
static const int While;
static const int For;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,Integer=258
	,Char=259
	,Single=260
	,Double=261
	,Id=262
	,IntegerValue=263
	,CharacterValue=264
	,SingleValue=265
	,DoubleValue=266
	,Print=267
	,Scan=268
	,Text=269
	,Address=270
	,If=271
	,Else=272
	,EQ=273
	,LE=274
	,GE=275
	,AND=276
	,OR=277
	,ADD=278
	,SUB=279
	,INC=280
	,DEC=281
	,While=282
	,For=283


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::Integer=258;
const int YY_parse_CLASS::Char=259;
const int YY_parse_CLASS::Single=260;
const int YY_parse_CLASS::Double=261;
const int YY_parse_CLASS::Id=262;
const int YY_parse_CLASS::IntegerValue=263;
const int YY_parse_CLASS::CharacterValue=264;
const int YY_parse_CLASS::SingleValue=265;
const int YY_parse_CLASS::DoubleValue=266;
const int YY_parse_CLASS::Print=267;
const int YY_parse_CLASS::Scan=268;
const int YY_parse_CLASS::Text=269;
const int YY_parse_CLASS::Address=270;
const int YY_parse_CLASS::If=271;
const int YY_parse_CLASS::Else=272;
const int YY_parse_CLASS::EQ=273;
const int YY_parse_CLASS::LE=274;
const int YY_parse_CLASS::GE=275;
const int YY_parse_CLASS::AND=276;
const int YY_parse_CLASS::OR=277;
const int YY_parse_CLASS::ADD=278;
const int YY_parse_CLASS::SUB=279;
const int YY_parse_CLASS::INC=280;
const int YY_parse_CLASS::DEC=281;
const int YY_parse_CLASS::While=282;
const int YY_parse_CLASS::For=283;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		140
#define	YYFLAG		-32768
#define	YYNTBASE	45

#define YYTRANSLATE(x) ((unsigned)(x) <= 283 ? yytranslate[x] : 73)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    39,     2,     2,     2,    36,    44,     2,    37,
    38,    34,    32,    43,    33,     2,    35,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    31,    41,
    42,    40,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    29,     2,    30,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    10,    12,    14,    16,    18,
    22,    26,    33,    40,    43,    46,    54,    62,    68,    72,
    76,    78,    82,    86,    90,    92,    96,    98,   101,   103,
   107,   109,   113,   115,   118,   120,   124,   126,   130,   132,
   134,   136,   138,   140,   144,   150,   166,   169,   174,   177,
   178,   180,   182,   184,   186,   188,   190,   193,   195,   197,
   199,   203,   204,   209,   210,   212
};

static const short yyrhs[] = {    46,
     0,    47,    46,     0,     0,    48,     0,    51,     0,    49,
     0,    62,     0,    63,     0,    50,     0,    29,    46,    30,
     0,    66,    64,    31,     0,    12,    72,    14,    69,    71,
    31,     0,    13,    72,    14,    70,    71,    31,     0,    52,
    31,     0,    61,    31,     0,    16,    72,    55,    71,    48,
    17,    48,     0,    16,    72,    55,    71,    48,    17,    51,
     0,    16,    72,    55,    71,    47,     0,    52,    32,    53,
     0,    52,    33,    53,     0,    53,     0,    53,    34,    54,
     0,    53,    35,    54,     0,    53,    36,    54,     0,    54,
     0,    37,    52,    38,     0,     7,     0,    33,     7,     0,
    67,     0,    55,    22,    56,     0,    56,     0,    56,    21,
    57,     0,    57,     0,    39,    57,     0,    58,     0,    37,
    55,    38,     0,    59,     0,    52,    60,    52,     0,    18,
     0,    40,     0,    41,     0,    19,     0,    20,     0,     7,
    42,    52,     0,    27,    37,    55,    38,    48,     0,    28,
    72,     7,    42,    67,    31,     7,    19,    67,    31,     7,
    23,    67,    71,    48,     0,     7,    65,     0,     7,    42,
    67,    65,     0,    43,    64,     0,     0,     3,     0,     4,
     0,     5,     0,     6,     0,     9,     0,    68,     0,    33,
    68,     0,     8,     0,    10,     0,    11,     0,    43,     7,
    69,     0,     0,    43,    44,     7,    70,     0,     0,    38,
     0,    37,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    32,    36,    37,    40,    41,    44,    45,    46,    47,    48,
    51,    82,   123,   147,   148,   151,   171,   189,   202,   206,
   209,   212,   215,   218,   221,   224,   227,   228,   229,   232,
   235,   238,   241,   244,   245,   248,   251,   254,   259,   260,
   261,   262,   263,   266,   271,   283,   307,   308,   311,   312,
   315,   316,   317,   318,   320,   321,   322,   326,   327,   328,
   331,   332,   335,   336,   339,   341
};

static const char * const yytname[] = {   "$","error","$illegal.","Integer",
"Char","Single","Double","Id","IntegerValue","CharacterValue","SingleValue",
"DoubleValue","Print","Scan","Text","Address","If","Else","EQ","LE","GE","AND",
"OR","ADD","SUB","INC","DEC","While","For","'{'","'}'","';'","'+'","'-'","'*'",
"'/'","'%'","'('","')'","'!'","'>'","'<'","'='","','","'&'","start","Code","Line",
"Statement","SimpleStatement","IfStatement","OpenIfStatement","ArithmaticExpression",
"Term","Factor","LogicExpression","LogicTerm","LogicFactor","NotFactor","Comparator",
"Operation","Assignment","WhileLoop","ForLoop","Variables","List","DataType",
"Value","NumberValue","Arguments","Addresses","RP","LP",""
};
#endif

static const short yyr1[] = {     0,
    45,    46,    46,    47,    47,    48,    48,    48,    48,    48,
    49,    49,    49,    49,    49,    50,    51,    51,    52,    52,
    52,    53,    53,    53,    53,    54,    54,    54,    54,    55,
    55,    56,    56,    57,    57,    58,    58,    59,    60,    60,
    60,    60,    60,    61,    62,    63,    64,    64,    65,    65,
    66,    66,    66,    66,    67,    67,    67,    68,    68,    68,
    69,    69,    70,    70,    71,    72
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     1,     1,     1,     1,     1,     3,
     3,     6,     6,     2,     2,     7,     7,     5,     3,     3,
     1,     3,     3,     3,     1,     3,     1,     2,     1,     3,
     1,     3,     1,     2,     1,     3,     1,     3,     1,     1,
     1,     1,     1,     3,     5,    15,     2,     4,     2,     0,
     1,     1,     1,     1,     1,     1,     2,     1,     1,     1,
     3,     0,     4,     0,     1,     1
};

static const short yydefact[] = {     3,
    51,    52,    53,    54,    27,    58,    55,    59,    60,     0,
     0,     0,     0,     0,     3,     0,     0,     1,     3,     4,
     6,     9,     5,     0,    21,    25,     0,     7,     8,     0,
    29,    56,     0,    66,     0,     0,     0,     0,     0,     0,
    28,    57,    27,     0,     2,    14,     0,     0,     0,     0,
     0,    15,    50,     0,    44,    62,    64,     0,     0,     0,
     0,    31,    33,    35,    37,     0,     0,    10,    26,    19,
    20,    22,    23,    24,     0,     0,    47,    11,     0,     0,
     0,     0,     0,     0,    34,    39,    42,    43,    40,    41,
     0,     0,    65,     0,     0,     0,     0,     0,    50,    49,
    62,     0,     0,     0,    36,    38,    30,    18,     4,    32,
     0,    45,     0,    48,    61,    12,    64,    13,     0,     0,
     0,    63,    16,    17,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    46,     0,     0,     0
};

static const short yydefgoto[] = {   138,
    18,    19,    20,    21,    22,    23,    24,    25,    26,    61,
    62,    63,    64,    65,    91,    27,    28,    29,    54,    77,
    30,    31,    32,    80,    82,    94,    35
};

static const short yypact[] = {    86,
-32768,-32768,-32768,-32768,   -27,-32768,-32768,-32768,-32768,     6,
     6,     6,    10,     6,    86,   100,    72,-32768,    86,-32768,
-32768,-32768,-32768,   -14,    82,-32768,    27,-32768,-32768,    53,
-32768,-32768,    72,-32768,    50,    59,    24,    24,    77,    56,
-32768,-32768,-32768,    34,-32768,-32768,    72,    72,    72,    72,
    72,-32768,     8,    57,    38,    61,    63,    24,    24,    36,
    -8,    79,-32768,-32768,-32768,     0,    70,-32768,-32768,    82,
    82,-32768,-32768,-32768,    16,    53,-32768,-32768,   131,   101,
    96,   101,   123,     7,-32768,-32768,-32768,-32768,-32768,-32768,
    72,    24,-32768,    86,    24,   121,    16,    29,   102,-32768,
    61,   113,   139,   116,-32768,    38,    79,-32768,   134,-32768,
     6,-32768,   122,-32768,-32768,-32768,    63,-32768,    86,    24,
   145,-32768,-32768,-32768,    -8,   138,   121,    16,   142,   129,
   121,   155,   143,    16,   101,   121,-32768,   165,   167,-32768
};

static const short yypgoto[] = {-32768,
    -7,    74,   -83,-32768,-32768,    51,   -17,    88,    71,   -35,
    80,   -49,-32768,-32768,-32768,-32768,-32768,-32768,    93,    75,
-32768,   -69,   -11,    76,    54,   -73,   -10
};


#define	YYLAST		177


static const short yytable[] = {    44,
    36,    37,    66,    39,    42,    99,   102,    40,   104,    85,
   109,    45,   112,    92,    33,    55,    46,    47,    48,    60,
    60,    92,    84,     6,     7,     8,     9,   113,    92,    93,
    43,     6,     7,     8,     9,   123,     6,    96,     8,     9,
    83,    60,    34,   129,   105,   110,    38,   123,    98,    75,
    76,   127,   137,    86,    87,    88,    16,    52,   130,    53,
    58,   136,    59,    56,   135,    47,    48,    47,    48,    47,
    48,    69,    57,   106,    60,    89,    90,    60,    43,     6,
     7,     8,     9,    67,   125,    68,    42,    78,     1,     2,
     3,     4,     5,     6,     7,     8,     9,    10,    11,    95,
   120,    12,    60,    79,    16,    81,    41,     6,    17,     8,
     9,    97,    13,    14,    15,    49,    50,    51,    16,    72,
    73,    74,    17,     1,     2,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    70,    71,   111,   101,    93,   103,
    86,    87,    88,   116,    76,   117,   118,    13,    14,    15,
   119,   126,   121,    16,    47,    48,   128,    17,   131,   132,
    69,   133,    89,    90,   139,   134,   140,   108,   100,   124,
   122,   107,     0,   114,     0,     0,   115
};

static const short yycheck[] = {    17,
    11,    12,    38,    14,    16,    75,    80,    15,    82,    59,
    94,    19,    96,    22,    42,    33,    31,    32,    33,    37,
    38,    22,    58,     8,     9,    10,    11,    97,    22,    38,
     7,     8,     9,    10,    11,   119,     8,    38,    10,    11,
    58,    59,    37,   127,    38,    95,    37,   131,    33,    42,
    43,   125,   136,    18,    19,    20,    33,    31,   128,     7,
    37,   135,    39,    14,   134,    32,    33,    32,    33,    32,
    33,    38,    14,    91,    92,    40,    41,    95,     7,     8,
     9,    10,    11,     7,   120,    30,    98,    31,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    21,
   111,    16,   120,    43,    33,    43,     7,     8,    37,    10,
    11,    42,    27,    28,    29,    34,    35,    36,    33,    49,
    50,    51,    37,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    47,    48,    16,     7,    38,    44,
    18,    19,    20,    31,    43,     7,    31,    27,    28,    29,
    17,     7,    31,    33,    32,    33,    19,    37,    17,    31,
    38,     7,    40,    41,     0,    23,     0,    94,    76,   119,
   117,    92,    -1,    99,    -1,    -1,   101
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 32 "converter.y"
{printf("valid\n");
              printf("%s",yyvsp[0].strVal);return(0);;
    break;}
case 2:
#line 36 "converter.y"
{ yyval.strVal=concat(concat(yyvsp[-1].strVal," \n"),yyvsp[0].strVal);
    break;}
case 3:
#line 37 "converter.y"
{yyval.strVal="";  ;
    break;}
case 4:
#line 40 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 5:
#line 41 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 6:
#line 44 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 7:
#line 45 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 8:
#line 46 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);  ;
    break;}
case 9:
#line 47 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 10:
#line 48 "converter.y"
{yyval.strVal=strdup(yyvsp[-1].strVal); ;
    break;}
case 11:
#line 51 "converter.y"
{    str="Dim "; 
                                              flag=0;
                                              variable=pop(&variablesStack);
                                              if(variable){
                                                flag=1;
                                                str=concat(str,variable);
                                                variable=pop(&variablesStack);
                                                while(variable){ 
                                                     str=concat(str," , ");
                                                    str=concat(str,variable);
                                                variable=pop(&variablesStack);  
                                                }
                                                str=concat(str," As ");
                                                str=concat(str,yyvsp[-2].strVal);
                                             }
                                             variable=pop(&variablesWithValuesStack);
                                             value=pop(&variablesValuesStack);
                                             while(variable){
                                                if(flag)
                                                  str=concat(str,", ");
                                                  str=concat(str,variable);
                                                  str=concat(str," As ");
                                                  str=concat(str,yyvsp[-2].strVal);
                                                  str=concat(str," = ");
                                                  str=concat(str,value);
                                                variable=pop(&variablesWithValuesStack);
                                                value=pop(&variablesValuesStack);
                                                flag=1;
                                             }
                                          yyval.strVal=str;
                                        ;
    break;}
case 12:
#line 82 "converter.y"
{ 
                                    str="Console.Write(";
                                    text=yyvsp[-3].strVal;
                                    counter=0;
                                    N=strlen(text);
                                    for(i=0;i<N-1;i++)
                                        if(text[i]=='\\' && text[i+1]=='n'){
                                           str=concat(str,"\"& vbcrlf &\"");
                                            i++;
                                        }
                                            
                                        else if(text[i]=='%' && (text[i+1]=='d' || text[i+1]=='c' || text[i+1]=='f' 
                                                                 || (text[i+1]=='l' && text[i+2]=='f' && (i=i+1) )))
                                        {  
                                            str=concat(str,"{");
                                            str=concat(str,stringValue(strdup(" "),3,counter));
                                            str=concat(str,"}");
                                           counter++;
                                           i+=1;
                                        }
                                        else
                                            str=append(str,text[i]);
                                        
                                     str=append(str,'"');
                                    while(counter > 0){
                                       variable=pop(&variablesStack);
                                       if(variable)
                                       {
                                           str=concat(str," , ");
                                           str=concat(str,variable);
                                       }
                                       else
                                           yyerror("Not enough arguments");
                                       counter--;
                                   }
                                   if(pop(&variablesStack))
                                       yyerror("Too many arguments");
                                   
                                    yyval.strVal=concat(str,") ");
                                    free(str);
                                  ;
    break;}
case 13:
#line 123 "converter.y"
{ str="";
                                    text=yyvsp[-3].strVal;
                                    for(i=1;i<strlen(text)-1;i++)
                                        if(text[i]==' ')
                                            continue;
                                        else if(text[i]=='%' && (text[i+1]=='d' || text[i+1]=='c' || text[i+1]=='f' 
                                                                 || (text[i+1]=='l' && text[i+2]=='f' && (i=i+1) )))
                                        { 
                                          variable=pop(&variablesStack);
                                          if(variable)
                                          str=concat(str,concat(variable," = Console.ReadLine()\n"));
                                          else
                                           yyerror("Not enough arguments");
                                           i+=1;
                                        }
                                       else{
                                          yyerror("Invalid string in scanf");
                                           break;
                                       }
                                   if(pop(&variablesStack))
                                       yyerror("Too many arguments");
                                    str[strlen(str)-1]='\0';
                                    yyval.strVal=str;
                                  ;
    break;}
case 14:
#line 147 "converter.y"
{yyval.strVal=strdup(yyvsp[-1].strVal); ;
    break;}
case 15:
#line 148 "converter.y"
{yyval.strVal=strdup(yyvsp[-1].strVal); ;
    break;}
case 16:
#line 151 "converter.y"
{
                                str=concat("If ",yyvsp[-4].strVal);
                                str=concat(str,strdup(" Then\n\t"));
                                buff=strdup(yyvsp[-2].strVal);
                                for(i=0;i<strlen(buff);i++)
                                    if(buff[i]=='\n')
                                        str=concat(str,"\n\t");
                                    else
                                         str=append(str,buff[i]);
                                str=concat(str,strdup("\nElse\n\t"));
                                buff=strdup(yyvsp[0].strVal);
                                for(i=0;i<strlen(buff);i++)
                                     if(buff[i]=='\n')
                                      str=concat(str,"\n\t");
                                     else
                                          str=append(str,buff[i]);
                                yyval.strVal=concat(str,strdup("\nEnd If"));
                                ;
    break;}
case 17:
#line 171 "converter.y"
{
                               str=concat("If ",yyvsp[-4].strVal);
                               str=concat(str," Then\n\t");
                               buff=yyvsp[-2].strVal;
                                for(i=0;i<strlen(buff);i++)
                                    if(buff[i]=='\n')
                                        str=concat(str,"\n\t");
                                    else
                                         str=append(str,buff[i]);
                                str=concat(str,"\nElse\n\t");
                                buff=yyvsp[0].strVal;
                                for(i=0;i<strlen(buff);i++)
                                    if(buff[i]=='\n')
                                        str=concat(str,"\n\t");
                                    else
                                         str=append(str,buff[i]);
                                yyval.strVal=concat(str,"\nEnd If");
                                ;
    break;}
case 18:
#line 189 "converter.y"
{ 
                                str=concat("If ",yyvsp[-2].strVal);
                                str=concat(str," Then\n\t");
                                buff=yyvsp[0].strVal;
                                for(i=0;i<strlen(buff);i++)
                                     if(buff[i]=='\n')
                                        str=concat(str,"\n\t");
                                    else
                                         str=append(str,buff[i]);
                               yyval.strVal=concat(str,"\nEnd If");
                                ;
    break;}
case 19:
#line 202 "converter.y"
{
                                   str=concat(yyvsp[-2].strVal,strdup(" + "));
                                   yyval.strVal=concat(str,yyvsp[0].strVal);
                                  ;
    break;}
case 20:
#line 206 "converter.y"
{ str=concat(yyvsp[-2].strVal," - ");
                                   yyval.strVal=concat(str,yyvsp[0].strVal);
                                  ;
    break;}
case 21:
#line 209 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 22:
#line 212 "converter.y"
{  str=concat(yyvsp[-2].strVal," * ");
                              yyval.strVal=concat(str,yyvsp[0].strVal);
                            ;
    break;}
case 23:
#line 215 "converter.y"
{  str=concat(yyvsp[-2].strVal," / ");
                              yyval.strVal=concat(str,yyvsp[0].strVal);
                            ;
    break;}
case 24:
#line 218 "converter.y"
{ str=concat(yyvsp[-2].strVal," Mod ");
                             yyval.strVal=concat(str,yyvsp[0].strVal);
                            ;
    break;}
case 25:
#line 221 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 26:
#line 224 "converter.y"
{ str=concat("( ",yyvsp[-1].strVal);
                                        yyval.strVal=concat(str," )");
                                      ;
    break;}
case 27:
#line 227 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 28:
#line 228 "converter.y"
{ yyval.strVal=concat("-",yyvsp[0].strVal);;
    break;}
case 29:
#line 229 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal); ;
    break;}
case 30:
#line 232 "converter.y"
{ str=concat(yyvsp[-2].strVal," Or ");
                                                 yyval.strVal=concat(str,yyvsp[0].strVal);        
                                                  ;
    break;}
case 31:
#line 235 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 32:
#line 238 "converter.y"
{ str=concat(yyvsp[-2].strVal," And ");
                                         yyval.strVal=concat(str,yyvsp[0].strVal);
                                         ;
    break;}
case 33:
#line 241 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 34:
#line 244 "converter.y"
{ yyval.strVal=concat("Not ",yyvsp[0].strVal); ;
    break;}
case 35:
#line 245 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 36:
#line 248 "converter.y"
{ str=concat("( ",yyvsp[-1].strVal);
                                         yyval.strVal=concat(str," )");
                                    ;
    break;}
case 37:
#line 251 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 38:
#line 254 "converter.y"
{ str=concat(yyvsp[-2].strVal,yyvsp[-1].strVal);
                                                                  yyval.strVal=concat(str,yyvsp[0].strVal);
                                                                 ;
    break;}
case 39:
#line 259 "converter.y"
{yyval.strVal= " = " ;;
    break;}
case 40:
#line 260 "converter.y"
{yyval.strVal= " > " ;;
    break;}
case 41:
#line 261 "converter.y"
{yyval.strVal= " < " ;;
    break;}
case 42:
#line 262 "converter.y"
{yyval.strVal= " <= " ;;
    break;}
case 43:
#line 263 "converter.y"
{yyval.strVal= " >= " ;;
    break;}
case 44:
#line 266 "converter.y"
{    str=concat(yyvsp[-2].strVal,strdup(" = "));
                                              yyval.strVal=concat(str,strdup(yyvsp[0].strVal));
                                         ;
    break;}
case 45:
#line 271 "converter.y"
{   str=concat("While ",yyvsp[-2].strVal);
                                                       str=concat(str,"\n\t");
                                                       buff=yyvsp[0].strVal;
                                                       for(i=0;i<strlen(buff);i++)
                                                          if(buff[i]=='\n')
                                                              str=concat(str,"\n\t");
                                                           else
                                                               str=append(str,buff[i]);
                                                        yyval.strVal=concat(str,"\nEnd While");;
    break;}
case 46:
#line 284 "converter.y"
{  if(strcmp(yyvsp[-12].strVal,yyvsp[-8].strVal)!=0
                                                            || strcmp(yyvsp[-8].strVal,yyvsp[-4].strVal)!=0 )
                                                            yyerror(" Index of for loop must be the same ");
                                                            str=concat("For ",yyvsp[-12].strVal);
                                                            str=concat(str," = ");
                                                            str=concat(str,yyvsp[-10].strVal);
                                                            str=concat(str," To ");
                                                            str=concat(str,yyvsp[-6].strVal);
                                                            str=concat(str," Step ");
                                                            str=concat(str,yyvsp[-2].strVal);
                                                            str=concat(str,"\n\t");
                                                            buff=yyvsp[0].strVal;
                                                           for(i=0;i<strlen(buff);i++)
                                                            if(buff[i]=='\n')
                                                                str=concat(str,"\n\t");
                                                           else
                                                               str=append(str,buff[i]);
                                                           str=concat(str,"\nNext ");
                                                           yyval.strVal=concat(str,yyvsp[-12].strVal);
                                                           ;
    break;}
case 47:
#line 307 "converter.y"
{ push(&variablesStack,yyvsp[-1].strVal); ;
    break;}
case 48:
#line 308 "converter.y"
{ push(&variablesWithValuesStack,yyvsp[-3].strVal);
                      push(&variablesValuesStack,yyvsp[-1].strVal); ;
    break;}
case 51:
#line 315 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 52:
#line 316 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 53:
#line 317 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 54:
#line 318 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 55:
#line 320 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 56:
#line 321 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 57:
#line 322 "converter.y"
{ yyval.strVal=strdup(" -");
                    yyval.strVal=concat(yyval.strVal,strdup(yyvsp[0].strVal));;
    break;}
case 58:
#line 326 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 59:
#line 327 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 60:
#line 328 "converter.y"
{yyval.strVal=strdup(yyvsp[0].strVal);;
    break;}
case 61:
#line 331 "converter.y"
{ push(&variablesStack,yyvsp[-1].strVal); ;
    break;}
case 63:
#line 335 "converter.y"
{ push(&variablesStack,yyvsp[-1].strVal); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 344 "converter.y"

int yyerror(char* s){fprintf(stderr,"line %d :%s\n",lineNb,s);}
int main(void){ yyparse();}
